---
title: "Analysis of class surveys"
subtitle: "Table 1"
author: "Katie, Priyanka, Naira, Alex, Kaeya, Taneesha"
date: last-modified
published-title: "Updated"
editor: visual
format: html
code-copy: true
execute:
  message: false
  warning: false
  echo: false
  cache: true
---

```{r}
# load any other packages and read data here
library(tidyverse)
```

## Executive summary

We took the data from the PSTAT 197A capstone survey and sought to find if there were any correlations and connections in the data that may help us better understand the students taking the capstone. We used R to do our data analysis and came up with guiding questions that directed our research. Our findings are summarized in this document.

## Data description

The dataset was obtained from a survey that all 2025 Fall Quarter PSTAT 197A students completed. Personal identifying information was removed to ensure anonymity. Students were asked about classes they took, whether they have done research, what year they were, what preference for projects they have, etc. Students were informed that this data would be used by the class, and had the option to opt out of being in the dataset.

## Questions of interest

We sought to understand the relationship between coursework and a student's proficiency/curiosity. Our analysis addressed three questions:

1.  Does there exists a relationship between student's preference for non-industry projects and any other variables.
2.  Does taking CMPSC 9 (**Intermediate Python Programming**) versus CMPSC 16 (**Problem Solving with Computers I**) has any relation to self rated proficiency level in coding?
3.  Do people who have done research have more or less domains of interest compared to people who have not done research?

## Findings

For question three, we found that the mean number of domains of interest between students who have participated in research versus those who have not are similar in value, with the variance of the research group being higher. This higher variance could stem from the fact that there are more individuals who had done research (around double). Additionally, looking at the two distributions, those who had done research had more of a bell shaped curve, skewed to the right, with a peak at 3 domains of interest. On the other hand, those who had not done research had almost a ‘uniform’ distribution, with equal number of students choosing 2, 3, 4, and 5 domains of interest. Lastly, we conducted a t-test to see if there was a statistically significant difference between the two means of domains of interest. We got a p-value of 0.6418, which is greater than 0.05 (alpha level), thus we conclude there is no significant difference between the two means. 
